// File is autogenerated, do not modify here, see
// generator and template: templates/cmd_main.go.tpl

package ${SERVICE}

import "${MODULE}/rpc/${SERVICE}"

type Server struct {}
var _ ${SERVICE}.${SERVICE_CAMEL}Server = &Server{}

func (svc *Server) Shutdown() {}

